default['test_1']['name'] = 'test_1'
default['test_1']['channel'] = ''
default['test_1']['install_version'] = ''
default['test_1']['automate_name'] = ''
default['test_1']['jq_url'] = 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
